###
POST http://localhost:8080/employees

###
PUT http://localhost:8080/employees/{{id}}

###
GET http://localhost:8080/employees/{{id}}

###
DELETE http://localhost:8080/employees/{{id}}

###
GET http://localhost:8080/employees/salaryHigherThan

###
GET http://localhost:8080/employees/withHighestSalary

###
GET http://localhost:8080/employees

###
GET http://localhost:8080/employees/page

###
POST http://localhost:8080/employees/upload

###
GET http://localhost:8080/employees/{{id}}/fullInfo

###
POST http://localhost:8080/report

###
GET http://localhost:8080/report/{{id}}

###
POST http://localhost:8080/report/disk

###
GET http://localhost:8080/report/{{id}}/disk